-- Bootstrap schemas and stage for ADF landings
CREATE DATABASE IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS RAW.BRONZE;
CREATE SCHEMA IF NOT EXISTS RAW.STREAMING;

CREATE STAGE IF NOT EXISTS RAW.BRONZE.LANDING_STAGE
  URL='azure://<storage-account>.blob.core.windows.net/landing'
  STORAGE_INTEGRATION = azure_ext_int;

-- Base bronze tables populated by COPY/Snowpipe/ADF copy activity
CREATE OR REPLACE TABLE RAW.BRONZE.TRANSACTIONS (
  transaction_id NUMBER,
  card_id NUMBER,
  merchant STRING,
  amount NUMBER(18,2),
  currency STRING,
  status STRING,
  event_ts TIMESTAMP_NTZ,
  landed_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  _file STRING,
  _row NUMBER
);

CREATE OR REPLACE TABLE RAW.BRONZE.CUSTOMERS (
  customer_id NUMBER,
  full_name STRING,
  email STRING,
  phone STRING,
  address STRING,
  city STRING,
  state_code STRING,
  landed_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  _file STRING,
  _row NUMBER
);

CREATE OR REPLACE TABLE RAW.BRONZE.CARDS (
  card_id NUMBER,
  customer_id NUMBER,
  card_number STRING,
  status STRING,
  credit_limit NUMBER(18,2),
  available_limit NUMBER(18,2),
  landed_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  _file STRING,
  _row NUMBER
);

-- Streams to capture changes
CREATE OR REPLACE STREAM RAW.BRONZE.TRANSACTIONS_STREAM ON TABLE RAW.BRONZE.TRANSACTIONS APPEND_ONLY = FALSE;
CREATE OR REPLACE STREAM RAW.BRONZE.CUSTOMERS_STREAM ON TABLE RAW.BRONZE.CUSTOMERS APPEND_ONLY = FALSE;
CREATE OR REPLACE STREAM RAW.BRONZE.CARDS_STREAM ON TABLE RAW.BRONZE.CARDS APPEND_ONLY = FALSE;

-- Curated raw tables fed by streams (keeps latest values)
CREATE OR REPLACE TABLE RAW.STREAMING.TRANSACTIONS LIKE RAW.BRONZE.TRANSACTIONS;
CREATE OR REPLACE TABLE RAW.STREAMING.CUSTOMERS LIKE RAW.BRONZE.CUSTOMERS;
CREATE OR REPLACE TABLE RAW.STREAMING.CARDS LIKE RAW.BRONZE.CARDS;

CREATE OR REPLACE TASK RAW.STREAMING.MERGE_TRANSACTIONS_TASK
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 0/20 * * * * UTC'
AS
MERGE INTO RAW.STREAMING.TRANSACTIONS tgt
USING (
  SELECT * FROM RAW.BRONZE.TRANSACTIONS_STREAM
) src
ON tgt.TRANSACTION_ID = src.TRANSACTION_ID
WHEN MATCHED THEN UPDATE SET
  CARD_ID = src.CARD_ID,
  MERCHANT = src.MERCHANT,
  AMOUNT = src.AMOUNT,
  CURRENCY = src.CURRENCY,
  STATUS = src.STATUS,
  EVENT_TS = src.EVENT_TS,
  LANDED_AT = COALESCE(src.LANDED_AT, CURRENT_TIMESTAMP()),
  _FILE = src._FILE,
  _ROW = src._ROW
WHEN NOT MATCHED THEN INSERT VALUES
  (src.TRANSACTION_ID, src.CARD_ID, src.MERCHANT, src.AMOUNT, src.CURRENCY, src.STATUS, src.EVENT_TS, COALESCE(src.LANDED_AT, CURRENT_TIMESTAMP()), src._FILE, src._ROW);

CREATE OR REPLACE TASK RAW.STREAMING.MERGE_CUSTOMERS_TASK
  WAREHOUSE = COMPUTE_WH
  AFTER RAW.STREAMING.MERGE_TRANSACTIONS_TASK
AS
MERGE INTO RAW.STREAMING.CUSTOMERS tgt
USING (SELECT * FROM RAW.BRONZE.CUSTOMERS_STREAM) src
ON tgt.CUSTOMER_ID = src.CUSTOMER_ID
WHEN MATCHED THEN UPDATE SET
  FULL_NAME = src.FULL_NAME,
  EMAIL = src.EMAIL,
  PHONE = src.PHONE,
  ADDRESS = src.ADDRESS,
  CITY = src.CITY,
  STATE_CODE = src.STATE_CODE,
  LANDED_AT = COALESCE(src.LANDED_AT, CURRENT_TIMESTAMP()),
  _FILE = src._FILE,
  _ROW = src._ROW
WHEN NOT MATCHED THEN INSERT VALUES
  (src.CUSTOMER_ID, src.FULL_NAME, src.EMAIL, src.PHONE, src.ADDRESS, src.CITY, src.STATE_CODE, COALESCE(src.LANDED_AT, CURRENT_TIMESTAMP()), src._FILE, src._ROW);

CREATE OR REPLACE TASK RAW.STREAMING.MERGE_CARDS_TASK
  WAREHOUSE = COMPUTE_WH
  AFTER RAW.STREAMING.MERGE_CUSTOMERS_TASK
AS
MERGE INTO RAW.STREAMING.CARDS tgt
USING (SELECT * FROM RAW.BRONZE.CARDS_STREAM) src
ON tgt.CARD_ID = src.CARD_ID
WHEN MATCHED THEN UPDATE SET
  CUSTOMER_ID = src.CUSTOMER_ID,
  CARD_NUMBER = src.CARD_NUMBER,
  STATUS = src.STATUS,
  CREDIT_LIMIT = src.CREDIT_LIMIT,
  AVAILABLE_LIMIT = src.AVAILABLE_LIMIT,
  LANDED_AT = COALESCE(src.LANDED_AT, CURRENT_TIMESTAMP()),
  _FILE = src._FILE,
  _ROW = src._ROW
WHEN NOT MATCHED THEN INSERT VALUES
  (src.CARD_ID, src.CUSTOMER_ID, src.CARD_NUMBER, src.STATUS, src.CREDIT_LIMIT, src.AVAILABLE_LIMIT, COALESCE(src.LANDED_AT, CURRENT_TIMESTAMP()), src._FILE, src._ROW);

-- Enable the task chain
ALTER TASK IF EXISTS RAW.STREAMING.MERGE_TRANSACTIONS_TASK RESUME;
ALTER TASK IF EXISTS RAW.STREAMING.MERGE_CUSTOMERS_TASK RESUME;
ALTER TASK IF EXISTS RAW.STREAMING.MERGE_CARDS_TASK RESUME;
